version: '3.8'
services:
  mass-spec-server:
    build: .
    container_name: MassSpectrumWeb
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data  # Вот здесь магия сохранения данных
    environment:
      - DATA_PATH=/data
      - API_KEY=3fjeiu289fh8238h84fh781290
      - TZ=Europe/Moscow
    restart: unless-stopped