version: '3.8'
services:
  mass-spec-server:
    build: .
    container_name: mass-spec-server
    ports:
      - "8080:8080"
    volumes:
      # Все содержимое папки ./data на Windows попадет в /data внутри Linux
      - ./data:/data 
    environment:
      - DATA_PATH=/data
      - TZ=Europe/Moscow
    restart: unless-stopped